services:
  frontend:
    container_name: latex-ai-frontend
    build:
      context: ./frontend
    restart: unless-stopped
    ports:
      - 5173:5173
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend

  backend:
    container_name: latex-ai-backend
    build:
      context: ./backend
    restart: unless-stopped
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - ./backend/src:/app/src
